### ISSUE TITLE
"Gluetun returned 401", cannot get the forwarded port

### ISSUE THREAD

**Issue by NadCat1** [t-anc/GSP-Qbittorent-Gluetun-sync-port-mod#27]
This is probably me doing something wrong but I'm not sure what.

I'm running Docker on my Synology NAS. Gluetun and qbittorrent are run together in a project. I first created the API key with docker run --rm qmcgaw/gluetun genkey. Then, I created the config.toml file and added the key to both the config and the compose files.

This is my config.toml file:

```
[[roles]]
name = "t-anc/GSP-Qbittorent-Gluetun-sync-port-mod"
routes = ["GET /v1/openvpn/portforwarded"]
auth = "apikey"
apikey = "my api key"
```

This is my compose.yaml:

```
services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 8000:8000/tcp # HTTP control server
      - 8888:8888/tcp # HTTP proxy
      - 8388:8388/tcp # Shadowsocks
      - 8388:8388/udp # Shadowsocks
      - 8090:8090 # port for qbittorrent web ui
    volumes:
      - /volume1/docker/gluetun:/gluetun
      - "./config.toml:/gluetun/auth/config.toml:ro"
    environment:
      - VPN_SERVICE_PROVIDER=protonvpn
      - VPN_PORT_FORWARDING=on
      - VPN_PORT_FORWARDING_STATUS_FILE=/gluetun/tmp/forwarded_port
      - OPENVPN_USER=<user>
      - OPENVPN_PASSWORD=<password>
    network_mode: synobridge
    labels:
      - com.centurylinklabs.watchtower.enable=false
    restart: unless-stopped
  qbittorrent:
    image: linuxserver/qbittorrent:5.0.1-libtorrentv1
    container_name: qbittorrent
    environment:
      - PUID=1027
      - PGID=100
      - TZ=GH
      - WEBUI_PORT=8090
      - DOCKER_MODS=ghcr.io/t-anc/gsp-qbittorent-gluetun-sync-port-mod:main
      - GSP_GTN_API_KEY=my_api_key
      - GSP_MINIMAL_LOGS=false
    volumes:
      - /volume1/docker/qbittorrent:/config
      - /volume1/data/torrents:/data/torrents
    network_mode: service:gluetun # run on the vpn network
    depends_on:
      - gluetun
    restart: unless-stopped
```

This is what the log shows:

```
gluetun        | 2025-07-27T15:42:46Z INFO [http server] 401 GET /v1/openvpn/portforwarded wrote 13B to 127.0.0.1:37808 in 373.095763ms
  qbittorrent    | 07/27/25 15:42:46 [GSP] - [ERROR] Gluetun returned 401. Is Gluetun's authentication correctly configured ? See https://github.com/t-anc/GSP-Qbittorent-Gluetun-sync-port-mod#gluetun
qbittorrent    | 07/27/25 15:42:46 [GSP] - Init checks failed, exiting the mod. You can disable init checks by setting "GSP_SKIP_INIT_CHECKS=true".
```

I'm not really sure what I'm doing wrong here, as far as I can tell I'm doing everything according to the manual.

**Comment by t-anc** [comment]
Aah, and do you need gluetun's control server outside of those 2 containers ? Idk if an exposed port is still accesssible from within the container, and I see that you expose gluetun's port 8000. You can try to comment this to test.

**Comment by NadCat1** [comment]
Commenting out the control server port didn't work. I'm a bit confused about the debug setting, I added - GSP_DEBUG = true to the compose file but the log doesn't show any additional information. This is the entire qbit log:

```
qbittorrent    | [mod-init] Running Docker Modification Logic
qbittorrent    | [mod-init] Adding t-anc/gsp-qbittorent-gluetun-sync-port-mod:main to container
qbittorrent    | [mod-init] t-anc/gsp-qbittorent-gluetun-sync-port-mod:main at sha256:f7ca6a55081e69ce443a8266b01263c16279bbe795aac46ebe4f4e9f414479a0 has been previously applied skipping
qbittorrent    | [migrations] started
qbittorrent    | [migrations] no migrations found
qbittorrent    | usermod: no changes
qbittorrent    | ───────────────────────────────────────
qbittorrent    |
qbittorrent    |       ██╗     ███████╗██╗ ██████╗
qbittorrent    |       ██║     ██╔════╝██║██╔═══██╗
qbittorrent    |       ██║     ███████╗██║██║   ██║
qbittorrent    |       ██║     ╚════██║██║██║   ██║
qbittorrent    |       ███████╗███████║██║╚██████╔╝
qbittorrent    |       ╚══════╝╚══════╝╚═╝ ╚═════╝
qbittorrent    |
qbittorrent    |    Brought to you by linuxserver.io
qbittorrent    | ───────────────────────────────────────
qbittorrent    |
qbittorrent    | To support LSIO projects visit:
qbittorrent    | https://www.linuxserver.io/donate/
qbittorrent    |
qbittorrent    | ───────────────────────────────────────
qbittorrent    | GID/UID
qbittorrent    | ───────────────────────────────────────
qbittorrent    |
qbittorrent    | User UID:    1027
qbittorrent    | User GID:    100
qbittorrent    | ───────────────────────────────────────
qbittorrent    | Linuxserver.io version: release-5.0.1_v1.2.19-ls53
qbittorrent    | Build-date: 2024-11-17T06:53:53+00:00
qbittorrent    | ───────────────────────────────────────
qbittorrent    |
qbittorrent    | [custom-init] No custom files found, skipping...
qbittorrent    | +---------------------------------------------------------+
qbittorrent    | |           Gluetun sync port (GSP) mod loaded            |
qbittorrent    | +---------------------------------------------------------+
qbittorrent    | |  Qbittorrent address : http://localhost:8090            |
qbittorrent    | |  Gluetun address     : http://localhost:8000            |
qbittorrent    | |  GTN port index      : 1                                |
qbittorrent    | +---------------------------------------------------------+
qbittorrent    |
qbittorrent    | 07/29/25 05:29:43 [GSP] - Waiting for Qbittorrent WebUI ...
qbittorrent    | WebUI will be started shortly after internal preparations. Please wait...
qbittorrent    |
qbittorrent    | ******** Information ********
qbittorrent    | To control qBittorrent, access the WebUI at: http://localhost:8090
qbittorrent    | Connection to localhost (127.0.0.1) 8090 port [tcp/*] succeeded!
gluetun        | 2025-07-29T05:30:10Z INFO [http server] 401 GET /v1/openvpn/portforwarded wrote 13B to 127.0.0.1:47570 in 41.325µs
qbittorrent    | [ls.io-init] done.
qbittorrent    | 07/29/25 05:30:10 [GSP] - [ERROR] Gluetun returned 401. Is Gluetun's authentication correctly configured ? See https://github.com/t-anc/GSP-Qbittorent-Gluetun-sync-port-mod#gluetun
qbittorrent    | 07/29/25 05:30:10 [GSP] - Init checks failed, exiting the mod. You can disable init checks by setting "GSP_SKIP_INIT_CHECKS=true".
```

**Comment by styemmy** [comment]
i suddenly started getting this same error. 401 on gluetun. API key in config.toml and compose file are the same

**Comment by b-col** [comment]
> i suddenly started getting this same error. 401 on gluetun. API key in config.toml and compose file are the same

This is resolved, you just need to change the routes in config.toml and force update the Docker Mod if it's cached.

**Comment by styemmy** [comment]
> > i suddenly started getting this same error. 401 on gluetun. API key in config.toml and compose file are the same
> 
> This is resolved, you just need to change the routes in config.toml and force update the Docker Mod if it's cached.

what do you mean by changing the routes in config.toml? mine looks like this

`[[roles]]`
`name = "t-anc/GSP-Qbittorent-Gluetun-sync-port-mod"`
`routes = ["GET /v1/openvpn/portforwarded"]`
`auth = "apikey"`
`apikey = "mykey"`

I deleted and recreated the docker image to update the mod and i'm still having the same issue

**Comment by styemmy** [comment]
nevermind on the above, i saw the recent commits and changed the route to

`routes = ["GET /v1/portforward"]`

and it all works fine, cheers!
